language: python
python:
  - "2.7"
env:
  - DJANGO=1.7 DB=sqlite3
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
